### ISSUE TITLE
Missing sample files "bn-raw_wn-sa_wn.txt" , "lemma2synsets.<desired-languge>.txt"

### ISSUE THREAD

**Issue by amallik-ualberta** [SapienzaNLP/mulan#1]
The documentation says that we have to follow the code and instructions in the [SapienzaNLP/mwsd-datasets](https://github.com/SapienzaNLP/mwsd-datasets) repository to create these files. But, I haven't found files with similar names in that repository as well.

It would be great if you could provide samples for these files, so that we can look at the structure of the files and replicate them.

**Comment by poccio** [comment]
Hi!

First of all, thank you for your interest in our project and sorry for our late reply.

I just updated our README.md providing the information you asked. Besides, for both files, I also pointed to the associated sections in SapienzaNLP/mwsd-datasets whose instructions you need to run to generate them.

**Comment by amallik-ualberta** [comment]
Thanks a lot for your response. This was really helpful.
